### ISSUE TITLE
msViz hangs at 99% imported

### ISSUE THREAD

**Issue by glycoaddict** [optimusmoose/jsms#1]
![image](https://user-images.githubusercontent.com/19943098/70040490-9db14500-15f6-11ea-8324-cfc272749852.png)
Thanks for the nice work. Came across your software from your PlosOne and Bioinformatics papers.
This is on your 2.0 commit (d9f366a) as I couldn't work out how to run your Xflow commit.

I opened an mzml file, and the progress % went up but eventually hung at 99% for 45 min, at which point I closed it.
The viewer loads but nothing is loaded so it just gives me a blank grid. 
Do you have example data I can test on?

Thanks.

**Comment by glycoaddict** [comment]
update: tried a second file with only MS1 and it get to 100% but still not loading. JRE 8, MZML 1.1 using msconvert from Thermo orbitrap fusion .raw.

![image](https://user-images.githubusercontent.com/19943098/70041066-74dd7f80-15f7-11ea-831f-6031563744f4.png)

**Comment by optimusmoose** [comment]
Hi Matthew,
There is a bit of heavy lifting after the load process.

Did you increase from the default memory size using the command line
arguments in the readme?

Thanks,
Rob

**Comment by glycoaddict** [comment]
Hi Rob, I changed it to -Xmx4g and tried again. The file seems to have gone to 100% and I notice that the axes in the viewer have the correct ranges (in my case 20-40 min, m/z 300-2500).

But the plot is empty and the screen shows:
```
<html><body><h2>500 Internal Server Error</h2></body></html>
0 Pending Updates
0 points. Progress: unknown (press A to recompute)
No trace or envelope selected.
MZ: [589.839, 599.839]
RT: [19.903, 40.097]
INT: [Infinity, 0]
[ No point near mouse ]
```


The console displays this message if I press the key "a":

```
Dec 04, 2019 2:29:43 PM edu.msViz.mzTree.MzTree ensurePointIDs
WARNING: Failed to retrieve points for node. Future query results may be incomplete.
java.lang.NullPointerException
	at edu.msViz.mzTree.storage.HybridStorage$SQLEngine.selectPointIDsByNode(HybridStorage.java:767)
	at edu.msViz.mzTree.storage.HybridStorage.getNodePointIDs(HybridStorage.java:177)
	at edu.msViz.mzTree.MzTree.ensurePointIDs(MzTree.java:826)
	at edu.msViz.mzTree.MzTree.collectPointsWithinBounds(MzTree.java:800)
	at edu.msViz.mzTree.MzTree.query(MzTree.java:703)
	at edu.msViz.msHttpApi.MsDataServer.getPoints(MsDataServer.java:184)
	at spark.RouteImpl$1.handle(RouteImpl.java:72)
	at spark.http.matching.Routes.execute(Routes.java:61)
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:130)
	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1568)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:530)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:347)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:256)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by optimusmoose** [comment]
If you aren't get a file loaded message in the server console, it hasn't
loaded fully yet. Like I said, there is quite a long wait period at the
very end of the file load as the data structures are being built. Give it
as much memory as you can spare and some more time and see if it resolves
the issue. How large is the file in MB/GB?

**Comment by glycoaddict** [comment]
I used msconvert to take a subset of my larger file so its a smaller size at 184 MB. I gave it an hour over lunch. I also tried loading the .mzTree file. The export tab is clickable but shows no entries, if that helps.

**Comment by optimusmoose** [comment]
Is there any way we can get your input file to troubleshoot it?
Alternatively, you could see if you could reproduce it with a publicly
available file and send me the link.

Thanks,
Rob

**Comment by glycoaddict** [comment]
Hi Rob, you can find the file here https://hcpacrc.fugu-sg.org/u/78ZVbxdGVWn9xlVt/101a%20-%20HEK-AXL_500ng_OT_HCD30EThcD.mzML?l

This is the snippet from a replicate run to the raw file at https://www.ebi.ac.uk/pride/archive/projects/PXD009222/files
namely: https://www.ebi.ac.uk/pride/data/archive/2019/05/PXD009222/101a%20-%20HEK-AXL_500ng_OT_HCD30EThcD.raw

I hope this helps!

**Comment by optimusmoose** [comment]
Hi Matthew,
I'm sorry for the delay. I was traveling.

I just downloaded your file. I made sure I had the up to date release. I
followed the build instructions in the readme notes, then opened your file.
I didn't change the default memory size. It loaded in about three minutes
on my laptop, and the viewer launched successfully.

**Comment by glycoaddict** [comment]
It works! Previously I didn't do the build step as it seemed optional, but after installing JDK 8 and Maven, adding JDK 8 and Maven to path, the build worked. Prob my noob error in not building for my system.

Thanks so much!
